name: test
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }} Crystal ${{ matrix.crystal }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:   [ 'ubuntu', 'macos' ]
        crystal: [ '1.2', '1.3' ]
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install HTSLib (ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt update
          sudo apt install libhts-dev
      - name: Install HTSLib (macos)
        if: ${{ matrix.os == 'macos' }}
        run: |
          brew install htslib
      - name: Run tests
        run: |
          shards install
          crystal test/run_all.cr -- --chaos --paralel 4 --verbose
