name: test
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }} Crystal ${{ matrix.crystal }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:   [ 'ubuntu', 'macos' ]
        crystal: [ '1.8', '1.9' ]
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install latest HTSLib (ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt update -y
          sudo apt install -yq libcurl4-openssl-dev liblzma-dev libbz2-dev libdeflate-dev pkg-config
          git clone --recurse-submodules https://github.com/samtools/htslib
          cd htslib && autoreconf -i && make -j4 && sudo make install
      - name: Install HTSLib (macos)
        if: ${{ matrix.os == 'macos' }}
        run: |
          brew install htslib pkg-config
      - name: Run tests
        run: |
          shards install
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
          crystal test/run_all.cr -- --chaos --paralel 4 --verbose
