name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 1.0.0
      - name: Install HTSlib
        run: |
          sudo apt update
          sudo apt install libhts-dev
      - name: Run tests
        run: |
          shards install
          crystal test/run_all.cr -- --chaos --paralel 4 --verbose
