name: docs

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v7
      - uses: crystal-lang/install-crystal@v1
      - name: Install documentation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libhts-dev
      - name: Generate document
        run: crystal docs
      - name: Publish Documentation on GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
